from sqlalchemy import Column, String, Float, DateTime, ForeignKey, Text, Boolean
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.database import Base


class Recommendation(Base):
    """
    Recommendation model for personalized content and learning path suggestions.
    Generated by the recommendation engine based on learner profile and behavior.
    """
    __tablename__ = "recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    learner_id = Column(UUID(as_uuid=True), ForeignKey("learners.id", ondelete="CASCADE"), nullable=False)
    
    # Recommendation Type
    recommendation_type = Column(String(50))  # content, schedule, format, path, break
    
    # Recommended Item
    recommended_item_id = Column(UUID(as_uuid=True))  # Content ID, Path ID, etc.
    
    # Recommendation Details
    recommendation_data = Column(JSONB)  # Additional recommendation details
    
    # Confidence & Reasoning
    confidence_score = Column(Float)  # 0-1 scale
    reason = Column(Text)  # Human-readable explanation
    
    # User Response
    is_accepted = Column(Boolean)  # True if user accepted, False if rejected, None if pending
    user_feedback = Column(String(500))  # Optional user feedback
    
    # Priority & Status
    priority = Column(String(20), default='medium')  # low, medium, high, urgent
    status = Column(String(20), default='pending')  # pending, accepted, rejected, expired
    
    # Expiration
    expires_at = Column(DateTime)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    learner = relationship("Learner", back_populates="recommendations")

    def __repr__(self):
        return f"<Recommendation(id={self.id}, type={self.recommendation_type}, confidence={self.confidence_score})>"

    def to_dict(self):
        """Convert recommendation to dictionary"""
        return {
            "id": str(self.id),
            "learner_id": str(self.learner_id),
            "recommendation_type": self.recommendation_type,
            "recommended_item_id": str(self.recommended_item_id) if self.recommended_item_id else None,
            "recommendation_data": self.recommendation_data,
            "confidence_score": self.confidence_score,
            "reason": self.reason,
            "is_accepted": self.is_accepted,
            "user_feedback": self.user_feedback,
            "priority": self.priority,
            "status": self.status,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

# Made with Bob
